version: "3"
services:
    app:
      build: ./Docker/app
      environment:
        - DEBUG=app:*
      tty: true
      ports:
          - '3002:3000'
      volumes:
        - ./src:/app
      working_dir: /app
      command: npm run dev